---
# tasks file for mysql-role
- name: Install PreReq pre_packages
  yum: name='{{ pre_packages }}' state=present

- name: Add Repository
  yum_repository:
    name: MariaDB
    description: MariaDB Custom Repository
    baseurl: '{{ repo }}'
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes

- name: Install MySQL Packages
  yum: name='{{ mysql_packages }}' state=present

- name: Start MySQL service
  service: name=mariadb state=started

- name: Configure Database
  mysql_db: name='{{ db_name }}' state=present

- name: Create Database User
  mysql_user:
    name: '{{ mysql_user_name }}'
    password: '{{ mysql_user_password }}'
    priv: '{{ db_name }}.*:ALL'
    state: present